### ISSUE TITLE
iOS 15 Compatibility

### ISSUE THREAD

**Issue by FlorianWendelborn** [ajayyy/SponsorBlockSafari#1]
Are there any plans/is it even possible to port this extension to the new iOS 15 Safari Extensions API? If yes, will I be able to purchase the macOS version to use it on iOS 15 later this year?

![image](https://user-images.githubusercontent.com/1133858/123401155-ccab5500-d5a6-11eb-9fe3-fe427922f312.png)

<https://developer.apple.com/safari/extensions/>

**Comment by ajayyy** [comment]
Tracked here: https://github.com/ajayyy/SponsorBlock/wiki/Safari

I'll probably upload it as a seperate app set to free because it's not as easy to use on mobile.
